# Generated by Django 2.2.4 on 2019-09-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_id', models.CharField(max_length=300, verbose_name='ID do Curso')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('pular', models.BooleanField(verbose_name='Pular Questões?')),
                ('aleatoria', models.BooleanField(verbose_name='Questões aleatórias?')),
                ('exibicao_resp_corretas_ao_final', models.BooleanField(verbose_name='Exibir todas as respostas corretas no final da atividade?')),
                ('exibicao_resp_corretas_durante', models.BooleanField(verbose_name='Exibir a resposta correta a cada questão?')),
                ('perc_trof_bronze', models.IntegerField(verbose_name='Troféu de Bronze:')),
                ('perc_trof_prata', models.IntegerField(verbose_name='Troféu de Prata:')),
                ('perc_trof_ouro', models.IntegerField(verbose_name='Troféu de Ouro:')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(verbose_name=(models.CharField(max_length=100, verbose_name='Nome'),)),
        ),
    ]
