# Generated by Django 2.2.4 on 2020-02-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200226_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='visibilidade',
            new_name='visibilidade_publica',
        ),
    ]
