# Generated by Django 2.2.4 on 2020-02-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200226_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='aleatoria',
            field=models.CharField(max_length=100, verbose_name='Questões aleatórias?'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='exibicao_resp_corretas',
            field=models.CharField(max_length=100, verbose_name='Respostas Corretas:'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='pular',
            field=models.CharField(max_length=100, verbose_name='Pular Questões?'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='pontuacao',
            field=models.CharField(max_length=100, verbose_name='Pontuação'),
        ),
        migrations.AlterField(
            model_name='questao_verdadeiro_falso',
            name='pontuacao',
            field=models.CharField(max_length=100, verbose_name='Pontuação'),
        ),
    ]
