# Generated by Django 2.2.4 on 2020-02-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200227_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='visibilidade_publica',
            new_name='visibilidade',
        ),
    ]
