# Generated by Django 2.2.4 on 2020-03-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200227_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='pular',
        ),
        migrations.AddField(
            model_name='atividade',
            name='autor',
            field=models.CharField(default='desconhecido', max_length=100, verbose_name='Autor:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='turma',
            field=models.CharField(default='desconhecida', max_length=100, verbose_name='Turma:'),
            preserve_default=False,
        ),
    ]
