# Generated by Django 2.2.4 on 2020-03-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200305_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='autor',
            field=models.CharField(default='desconhecido', max_length=100, verbose_name='Autor:'),
            preserve_default=False,
        ),
    ]
