# Generated by Django 2.2.4 on 2020-04-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_questao_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='curso',
            field=models.CharField(default=None, max_length=100, verbose_name='Curso:'),
            preserve_default=False,
        ),
    ]
