# Generated by Django 2.2.4 on 2020-04-16 01:47

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import quizsophia.courses.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200413_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='turma',
        ),
        migrations.AddField(
            model_name='curso',
            name='alunos',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=quizsophia.courses.models.Usuario),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividade',
            name='autor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Usuario'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Curso'),
        ),
    ]
