# Generated by Django 2.2.4 on 2020-04-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200415_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='autor',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
